#!/bin/bash

FREQ=$(cpupower frequency-info -fm | grep "current CPU frequency:" | grep -Eo '[0-9]+([.][0-9]+)?')

if [[ "$FREQ" != *"."* ]]; then
  printf '%.2f GHz\n' 0.$FREQ
else
  printf '%.2f GHz\n' $FREQ
fi
